// ignore_for_file: avoid_print

import 'dart:convert' as convert;
import 'dart:io';
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:http/http.dart' as http;
import 'package:url_launcher/url_launcher.dart';

void main() {
  runApp(MyApp());
}

class Institution {
  final String name;
  final List<String> ips;
  final List<String> domains;

  const Institution({
    required this.name,
    required this.ips,
    required this.domains,
  });
}

enum DomainStatus { available, error, blocked, nx }

extension DomainStatusExtension on DomainStatus {
  String get name {
    switch (this) {
      case DomainStatus.available:
        return "Domenas neužblokuotas";
      case DomainStatus.blocked:
        return "Domenas užblokuotas";
      case DomainStatus.nx:
        return "Domenas neegzistuoja";
      case DomainStatus.error:
        return "Klaida";
    }
  }

  String get pluralName {
    switch (this) {
      case DomainStatus.available:
        return "Neužblokuoti domenai";
      case DomainStatus.blocked:
        return "Užblokuoti domenai";
      case DomainStatus.nx:
        return "Nebeegzistuojantys domenai";
      case DomainStatus.error:
        return "Klaidos";
    }
  }
}

class ResolvedDomain {
  final String domain;
  final List<String> resolvedIps;
  final DomainStatus status;

  ResolvedDomain({
    required this.domain,
    required this.resolvedIps,
    required this.status,
  });
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final data = [
    const Institution(
      name: "Lietuvos bankas",
      ips: ["193.219.8.149"],
      domains: [
        "riseglobal.us",
        "tradingteck.co",
        "toptrade.group",
        "24xfx.com",
        "24xforex.com",
        "nirotrade.com",
        "ltpays.com",
        "e-smp.com",
        "finmaxfx.com",
        "finmaxbo.com",
        "finmax.com",
        "titantradeclub.com",
        "terra-finance.co",
        "traderschain.com",
        "apcofx.com",
        "online.apzvalgos.com",
        "enigmaklubas.com",
        "yardoption.com",
        "tradingteck.com",
        "swtech.tilda.ws",
        "markets-soft.com",
        "edge.targetprovider.pro",
        "malleycapital.com",
        "marketssoft.net",
        "bitcoins-era.net",
        "fxpays.com",
        "getimmediateedge.com",
        "swlt.tilda.ws",
        "sky-way.lt",
        "skyway.capital",
        "10brokers.com",
        "everfxglobal.com",
        "bitcoinevolutionapp.com",
        "15min.lt-straipsniai.com",
        "forex-im.com",
        "ptbanc.com",
        "aspenholding.co",
        "libramethodapp.com",
        "trustfx.cc",
        "trustfx.io",
        "gbpay.lt",
        "lt.gbpay-oficial.info",
        "cgbanque.io",
        "ru.afxtrade.lt",
        "futureisbtc.com",
        "tv3-dabar.com",
        "investingcapital.com",
        "aftcapitals.com",
        "cfdtraderapp.safeoffer.to",
        "learnmakingcash.com",
        "aspenholding.com",
        "Blockgain.org",
        "delfi.naujienosjums.com",
        "strade24.com",
        "olympusmarkets.com",
        "vet-trade.com",
        "kriptokanapes.net",
        "cannabisfortuneapp.com",
        "kriptonaujiena.com",
        "ethereumcode2app.com",
        "verslozinios.com",
        "vz.kriptonaujienos.com",
        "citadel-fx.com",
        "red-trade.com",
        "algofxtrade.com",
        "skyway-capital.com",
        "ct-trade.com",
        "vesusfinansai.lt",
        "programusistemos.lt",
        "markets-invest.com",
        "get-financial.com",
        "marketscube.com",
        "midasglobe.com",
        "bbmtrade.com",
        "fx-dealer.com",
        "superbinary.com",
        "globalfxm.com"
      ],
    ),
    const Institution(
      name: "VVTAT",
      ips: ["193.219.10.98"],
      domains: [
        "svajoniuspinta.lt",
        "zidiniaikatilai.lt",
        "sildymoprekes.lt",
        "repe.lt",
      ],
    ),
    const Institution(
      name: "Lošimai",
      ips: ["62.77.154.37"],
      domains: [
        "betway.com",
        "unibet.lt",
        "unibet.com",
        "lt.unibet.com",
        "williamhill.com",
        "triobet.com",
        "m.triobet.com",
        "triobet.co.uk",
        "triobet1.com",
        "triobet2.com",
        "triobet3.com",
        "triobet4.com",
        "triobet5.com",
        "triobet15.com",
        "triobet17.com",
        "triobet18.com",
        "triobet19.com",
        "triobet20.com",
        "triobet21.com",
        "triobet22.com",
        "triobet23.com",
        "triobet24.com",
        "triobet25.com",
        "triobet26.com",
        "triobet27.com",
        "triobet28.com",
        "triobet33.com",
        "1triobet.com",
        "2triobet.com",
        "3triobet.com",
        "lt.unibet-3.com",
        "pokerstars.eu",
        "pokerstars.com",
        "pokerstars.asia",
        "pokerstars.be",
        "pokerstars.bg",
        "pokerstars.bi",
        "pokerstars.ca",
        "pokerstars.cards",
        "pokerstars.cc",
        "pokerstars.cm",
        "pokerstars.co",
        "pokerstars.co.mw",
        "pokerstars.co.tt",
        "pokerstars.co.uk",
        "pokerstars.com.ai",
        "pokerstars.com.gp",
        "pokerstars.com.gt",
        "pokerstars.com.kg",
        "pokerstars.com.lv",
        "pokerstars.com.mo",
        "pokerstars.com.mw",
        "pokerstars.com.ni",
        "pokerstars.com.sv",
        "pokerstars.com.tt",
        "marathonbet.co.uk",
        "mobile.marathonbet.co.uk",
        "marathonbet.com",
        "marathonbet0.com",
        "betmarathon.com",
        "marathonbet.cm",
        "marathonbet.info",
        "marathonbet.kg",
        "marathonbet.kz",
        "marathonbet.net",
        "marathonbet.org",
        "mobile.marathonbet.com",
        "pinnaclesports.com",
        "pinnaclesports.eu",
        "pinnaclesports.de",
        "pinnaclesports.co.uk",
        "unibet.de",
        "unibet.co.uk",
        "unibet.dk",
        "unibet.ee",
        "lt.unibet-2.com",
        "nordicbet.com",
        "nordicbet.fi",
        "nordicbet.no",
        "nordicbet.poker",
        "m.nordicbet.com",
        "188bet.com",
        "m.188bet.com",
        "188bet.co.uk",
        "m.188bet.co.uk",
        "triobet-10.com",
        "bet365.com",
        "bet365.com.pt",
        "mobile.bet365.com",
        "bet365.co",
        "bet365.co.uk",
        "bet365.cz",
        "bet365.dk",
        "mobile.bet365.dk",
        "bet365.com.au",
        "mobile.bet365.com.au",
        "lt.unibet-1.com",
        "triobet-11.com",
        "lt.unibet-4.com",
        "lt.unibet-9.com",
        "triobet-12.com",
        "fulltilt.eu",
        "fulltilt.asia",
        "fulltilt.biz",
        "fulltilt.ch",
        "fulltilt.com",
        "fulltilt.co.uk",
        "fulltilt.cz",
        "fulltilt.fi",
        "fulltiltpoker.asia",
        "fulltiltpoker.bb",
        "fulltiltpoker.biz",
        "fulltiltpoker.ch",
        "fulltiltpoker.co",
        "fulltiltpoker.com",
        "fulltiltpoker.com.py",
        "fulltiltpoker.cr",
        "fulltiltpoker.cz",
        "fulltiltpoker.eu",
        "fulltiltpoker.fi",
        "fulltiltpoker.gt",
        "fulltiltpoker.ie",
        "fulltiltpoker.in",
        "fulltiltpoker.info",
        "lt.unibet-8.com",
        "triobet-14.com",
        "pokerstars1.eu",
        "bet.pokerstars1.eu",
        "lt.unibet-7.com",
        "triobet-15.com",
        "lt.unibet-6.com",
        "triobet34.com",
        "betstars.eu",
        "betstars1.eu",
        "eurocasino.com",
        "bethard.com",
        "spinpalace.com",
        "32red.com",
        "partypoker.com",
        "winner.com",
        "888sport.com",
        "betfred.com",
        "casinoroom.com",
        "allslotscasino.com",
        "unibet.eu",
        "jetbull.com",
        "betrally.com",
        "europacasino.com",
        "lt.unibet-5.com",
        "titancasino.com",
        "lt.unibet-11.com",
        "lt.unibet-12.com",
        "mybet.com",
        "mybet.at",
        "mybet.ch",
        "mybet.cn",
        "mybet.co.in",
        "mybet.co.uk",
        "mybet.com.br",
        "mybet.cz",
        "mybet.de",
        "mybet.dk",
        "mybet.es",
        "mybet.gr",
        "mybet.hu",
        "mybet.info",
        "mybet.it",
        "mybet.lv",
        "paddypower.com",
        "paddypower.co.uk",
        "paddypower.com.au",
        "paddypower.ie",
        "sports.paddypower.mobi",
        "lt.unibet-13.com",
        "7spins.com",
        "365sb.com",
        "sbobet.com",
        "totesport.com",
        "spinstation.com",
        "lt.unibet-14.com",
        "pokerstarscasino.eu",
        "olybet.com",
        "wwin.com",
        "lt.unibet-15.com",
        "gdaycasino.com",
        "sportsbet.com.au",
        "wildjackpots.com",
        "lt.unibet-16.com",
        "lt.unibet-17.com",
        "888games.com",
        "888.casino.com",
        "energycasino.com",
        "lt.unibet-18.com",
        "betfair.com",
        "mrgreen.com",
        "lt.unibet-19.com",
        "lt.unibet-20.com",
        "betspin.com",
        "rizk.com",
        "guts.com",
        "metalcasino.com",
        "royalpanda.com",
        "1xbet.com",
        "1-x-bet.com",
        "1x-bet.com",
        "lt.unibet-21.com",
        "superlenny.com",
        "olimp.com",
        "788-sb.com",
        "parimatch.com",
        "pinnacle.com",
        "betmotion.com",
        "vbet.com",
        "lt.unibet-22.com",
        "288sb.com",
        "allsport365.com",
        "thrills.com",
        "lt.unibet-23.com",
        "288365.com",
        "comeon.com",
        "lt.unibet-24.com",
        "europalace.com",
        "lvbet.com",
        "lt.unibet-25.com",
        "fortuneroomcasino.com",
        "casinotropez.com",
        "lt.unibet-26.com",
        "piggspeak.com",
        "redkings.com",
        "bet.redkings.com",
        "casino.redkings.com",
        "poker.redkings.com",
        "365-808.com",
        "lt.unibet-27.com",
        "casinojefe.com",
        "sloty.com",
        "888poker.com",
        "38365365.com",
        "lt.unibet-28.com",
        "lt.unibet-29.com",
        "48-365365.com",
        "lt.unibet-30.com",
        "121-365sb.com",
        "dunder.com",
        "lt.unibet-31.com",
        "royalvegascasino.com",
        "redflushcasino.com",
        "babe.casino",
        "lt.unibet-32.com",
        "lt.playmillion.com",
        "playmillion.com",
        "nissicasino.com",
        "48365365.com",
        "bet3000.com",
        "lt.unibet-33.com",
        "jackpotcitycasino.com",
        "lt.unibet-34.com",
        "nutsbet.com",
        "lt.unibet-35.com",
        "488365.com",
        "18bet.com",
        "lt.unibet-36.com",
        "888ladies.com",
        "mostbet.com",
        "genesiscasino.com",
        "casinojoy.com",
        "platinumplaycasino.com",
        "extraspel.com",
        "kingbillycasino.com",
        "bitstarz.com",
        "casinolasvegas.com",
        "betwinner.com",
        "lt.unibet-37.com",
        "gamingclub.com",
        "lt.unibet-38.com",
        "mbet.com",
        "bitstarz13.com",
        "22bet.com",
        "1xslot.com",
        "evobet.com",
        "bitstarz14.com",
        "campeonbet.com",
        "lt.unibet-39.com",
        "z-bets.com",
        "vulkanbet.com",
        "casino-z.com",
        "casinochan.com",
        "riverbellecasino.com",
        "365838.com",
        "db-bet.com",
        "lt.unibet-40.com",
        "orientxpresscasino.com",
        "1xgjm.world",
        "playamo.com",
        "lt.unibet-41.com",
        "bitstarz15.com",
        "lt.unibet-42.com",
        "melbet.com",
        "bitstarz16.com",
        "betwinner1.com",
        "betwinner2.com",
        "betwinner3.com",
        "betwinner4.com",
        "betwinner5.com",
        "betwinner6.com",
        "betwinner7.com",
        "betwinner8.com",
        "betwinner9.com",
        "betwinner10.com",
        "betwinner11.com",
        "betwinner12.com",
        "betwinner13.com",
        "betwinner14.com",
        "betwinner15.com",
        "betwinner16.com",
        "betwinner17.com",
        "betwinner18.com",
        "betwinner19.com",
        "betwinner20.com",
        "betwinner21.com",
        "betwinner22.com",
        "betwinner23.com",
        "betwinner24.com",
        "betwinner25.com",
        "betwinner26.com",
        "oshi.io",
        "baocasino.com",
        "astekbet.com",
        "casinonic.com",
        "lt.unibet-43.com",
        "bitstarz17.com",
        "22bet1.com",
        "22bet3.com",
        "22bet4.com",
        "22bet5.com",
        "22bet6.com",
        "22bet7.com",
        "22bet9.com",
        "22bet10.com",
        "22bet11.com",
        "22bet.online",
        "22bet1.online",
        "slottyvegas.com",
        "gunsbet.com",
        "betcity.net",
        "betcityru.com",
        "bets-bc-mlpld.top",
        "cbet.gg",
        "lt.unibet-44.com",
        "bgo.com",
        "x1zcszvu.world",
        "x1qztfcu.world",
        "bitstarz18.com",
        "pokerdom.com",
        "sunmaker.com",
        "bet-andyou.com",
        "123365-sb.com",
        "lt.unibet-45.com",
        "bitstarz19.com",
        "betwinner27.com",
        "betwinner29.com",
        "betwinner30.com",
        "betwinner33.com",
        "betwinner34.com",
        "betwinner1.mob",
        "betwinner2.mob",
        "betwinner4.mob",
        "betwinner5.mob",
        "betwinner6.mob",
        "betwinner9.mob",
        "scasino.com",
        "fan-sport.com",
        "williamhillcasino.com",
        "betwinner1.mobi",
        "betwinner2.mobi",
        "betwinner4.mobi",
        "betwinner5.mobi",
        "betwinner6.mobi",
        "betwinner9.mobi",
        "bitstarz20.com",
        "lt.unibet-46.com",
        "lt.unibet-47.com",
        "melbet.org",
        "ewyzymelaa.top",
        "megapari.com",
        "spincasino.com",
        "lt.unibet-48.com",
        "lt.unibet-49.com",
        "22bet2.co",
        "bitstarz21.com",
        "1xslotmobi1.xyz",
        "1xslotmobi3.xyz",
        "1xslotmobi4.xyz",
        "1xslotmobi5.xyz",
        "1xslotmobi6.xyz",
        "1xslotmobi7.xyz",
        "1xslotmobi8.xyz",
        "1xslotmobi9.xyz",
        "1xslotmobi10.xyz",
        "lt.Unibet-50.com",
        "bitstarz22.com",
        "lt.unibet-52.com",
        "777.com",
        "22bet7.net",
        "lt.unibet-53.com",
        "bitstarz23.com",
        "betandyou.com",
        "campobet.com",
        "lt.unibet-54.com",
        "bitstarz24.com",
        "betregal.com",
        "astekbet10.mobi",
        "astekbet11.mobi",
        "astekbet12.mobi",
        "astekbet13.mobi",
        "astekbet14.mobi",
        "astekbet15.mobi",
        "astekbet16.mobi",
        "linebet.com",
        "22bet12.com",
        "betwinner35.com",
        "878365.com",
        "36500365.com",
        "28-365365.com",
        "28365-365.com",
        "635288.com",
        "48365-365.com",
        "635-288.com",
        "248365365.com",
        "sb-488.com",
        "365466.com",
        "68365365.com",
        "365-818.com",
        "lt.unibet-55.com",
        "bitstarz25.com",
        "asprobet.com",
        "lt.unibet-56.com",
        "1xslot1.xyz",
        "22bet13.com",
        "22bet14.com",
        "22bet15.com",
        "22bet16.com",
        "888casino.com",
        "348365365.com",
        "448365365.com",
        "365-288.com",
        "838365.com",
        "288-365.com",
        "365sport365.com",
        "sapphirebet.com",
        "mel73157.site",
        "bitstarz26.com",
        "365-588.com",
        "788-365.com",
        "365365918.com",
        "365212365.com",
        "365365868.com",
        "lt.unibet-57.com",
        "betingsite.com",
        "1zbet.net",
        "fan-sport1.com",
        "game-365.com",
        "365488.com",
        "288-563.com",
        "188sb.com",
        "356488.com",
        "boocasino.com",
        "sll365.com",
        "xparibet.com",
        "1xslot2.xyz",
        "1xslot3.xyz",
        "1xslot4.xyz",
        "1xslot5.xyz",
        "1xslot6.xyz",
        "1xslot7.xyz",
        "1xslot8.xyz",
        "1xslot9.xyz",
        "melbet4.com",
        "melbet5.com",
        "melbet6.com",
        "melbet8.com",
        "melbet9.com",
        "melbet10.com",
        "bitstarz27.com",
        "lt.unibet-58.com",
        "mariacasino.com",
        "slottica.com",
        "slottica1.com",
        "slottica2.com",
        "slottica3.com",
        "slottica4.com",
        "slottica5.com",
        "slottica6.com",
        "slottica7.com",
        "slottica8.com",
        "28365365.com",
        "betwinner42.com",
        "betwinner45.com",
        "betwinner46.com",
        "betwinner47.com",
        "lt.unibet-59.com",
        "bitstarz28.com",
        "pvpgmz6t.space",
        "lt.unibet-61.com",
        "188-sb.com",
        "536488.com",
        "1xslot41623.com",
        "lt.unibet-62.com",
        "pokerstarssports.eu",
        "1xslot78830.com",
        "lt.unibet-63.com",
        "betandyou1.com",
        "188-563.com",
        "653228.com",
        "356884.com",
        "betwinner50.com",
        "lt.unibet-64.com",
        "365-828.com",
        "365-838.com",
        "365-848.com",
        "365-858.com",
        "365-868.com",
        "365-878.com",
        "slottica10.com",
        "slottica11.com",
        "slottica12.com",
        "slottica13.com",
        "slottica14.com",
        "slottica15.com",
        "slottica16.com",
        "slottica17.com",
        "slottica18.com",
        "slottica19.com",
        "slottica20.com",
        "slottica21.com",
        "slottica22.com",
        "slottica23.com",
        "slottica24.com",
        "slottica25.com",
        "slottica26.com",
        "slottica27.com",
        "slottica28.com",
        "slottica29.com",
        "slottica30.com",
        "lt.unibet-65.com",
        "365066365.com",
        "bitstarz41.com",
        "megapari2.com",
        "megapari3.com",
        "megapari5.com",
        "megapari6.com",
        "megapari7.com",
        "megapari8.com",
        "lt.unibet-66.com",
        "365-88.com",
        "betwinner28.com",
        "megapari9.com",
        "megapari10.com",
        "lt.unibet-67.com",
        "365828.com",
        "egocasino.com",
        "egocasino1.com",
        "egocasino2.com",
        "egocasino3.com",
        "egocasino4.com",
        "egocasino5.com",
        "1.egocasino1.com",
        "2.egocasino1.com",
        "3.egocasino1.com",
        "4.egocasino1.com",
        "5.egocasino1.com",
        "6.egocasino1.com",
        "7.egocasino1.com",
        "8.egocasino1.com",
        "9.egocasino1.com",
        "10.egocasino1.com",
        "1.egocasino2.com",
        "2.egocasino2.com",
        "3.egocasino2.com",
        "4.egocasino2.com",
        "5.egocasino2.com",
        "6.egocasino2.com",
        "7.egocasino2.com",
        "8.egocasino2.com",
        "9.egocasino2.com",
        "10.egocasino2.com",
        "1.egocasino3.com",
        "2.egocasino3.com",
        "3.egocasino3.com",
        "4.egocasino3.com",
        "5.egocasino3.com",
        "6.egocasino3.com",
        "7.egocasino3.com",
        "8.egocasino3.com",
        "9.egocasino3.com",
        "10.egocasino3.com",
        "1.egocasino4.com",
        "2.egocasino4.com",
        "3.egocasino4.com",
        "4.egocasino4.com",
        "5.egocasino4.com",
        "6.egocasino4.com",
        "7.egocasino4.com",
        "8.egocasino4.com",
        "9.egocasino4.com",
        "10.egocasino4.com",
        "1.egocasino5.com",
        "2.egocasino5.com",
        "3.egocasino5.com",
        "4.egocasino5.com",
        "5.egocasino5.com",
        "6.egocasino5.com",
        "7.egocasino5.com",
        "8.egocasino5.com",
        "9.egocasino5.com",
        "10.egocasino5.com",
        "casoola.com",
        "jackpotsinaflash.com",
        "pelaa.com",
        "lt.unibet-68.com",
        "slotica555.com",
        "slottica333.com",
        "slottika1.com",
        "slottika3.com",
        "slottika6.com",
        "slottika7.com",
        "lt.unibet-69.com",
        "casinocruise.com",
        "lt.unibet-70.com",
        "vegashero.com",
        "regentplay.com",
        "spela.com",
        "casinogods.com",
        "lt.unibet-71.com",
        "powerplay.com",
        "lt.unibet-72.com",
        "slottika8.com",
        "slottika10.com",
        "kassu.com",
        "spinit.com",
        "lt.unibet-73.com",
        "casinolab.com",
        "casinoplanet.com",
        "barbadoscasino.com",
        "casinoluck.com",
        "lt.unibet-74.com",
        "slottika5.com",
        "7slottica7.com",
        "playfrank.com",
        "magicred.com",
        "billioncasino.com",
        "winnersmagic.com",
        "casinomia.com",
        "goprocasino.com",
        "vulkanvegas.com",
        "webbyslot.com",
        "sportsbet.io",
        "betmaster.io",
        "betwinner.ng",
        "nextcasino.com",
        "luckland.com",
        "casiplay.com",
        "wildslots.com",
        "casinosuperlines.net",
        "188563.com",
        "pokies2go.com",
        "jackiejackpot.com",
        "atlanticspins.com",
        "neptuneplay.com",
        "slottica-play.com",
        "2slottica.com",
        "3slottica.com",
        "4slottica.com",
        "8slottica.com",
        "9slottica.com",
        "10slottica.com",
        "11slottica.com",
        "15slottica.com",
        "betiton.com",
        "agentspinner.com",
        "kokoyoko.space",
        "casinoextra.com",
        "mrplay.com",
        "griffoncasino.com",
        "hazcasino.com",
        "vegasplus.com",
        "vegac24.com",
        "bongo.gg",
        "38-365365.com",
        "vegazcasino.com",
        "zenbetting.com",
        "tsars.com",
        "casinoin.io",
        "dafabet.com",
        "sportdafa.net",
        "1slottica.com",
        "5slottica.com",
        "13slottica.com",
        "mirblackpant.com",
        "mirtosecup.com",
        "mirbigleague.com",
        "mirbluejean.com",
        "wineeater.fun",
        "pin1111.com",
        "a93kfnds.com",
        "soprm6502.com",
        "4kingslots.com",
        "madmoneycasino.com",
        "38365-365.com",
        "gratorama.com",
        "cashmio.com",
        "starsweb.pokerstarscasino.com",
        "zencasino.com",
        "goldenlinecasino.com",
        "fruityvegas.co.uk",
        "energywin.com",
        "arcanebet.com",
        "wcasino-online.net",
        "vespercasino.com",
        "betcruise.com",
        "plazaroyal.com",
        "spacelilly.com",
        "300tsars.com",
        "200tsars.com",
        "100tsars.com",
        "horuscasino.com",
        "bongogg.com",
        "bongogaming.com",
        "888starz.bet",
        "888starz1.bet",
        "888starz2.bet",
        "888starz3.bet",
        "888starz4.bet",
        "888starz5.bet",
        "casino.partycasino.com",
        "12slottica.com",
        "16slottica.com",
        "55tsars.com",
        "44tsars.com",
        "33tsars.com",
        "22tsars.com",
        "11tsars.com",
        "ph.casino",
        "spinmillion13.com",
        "webbyslot17.com",
        "webbyslot18.com",
        "webbyslot19.com",
        "webbyslot20.com",
        "tsars1.com",
        "tsars2.com",
        "tsars3.com",
        "tsars4.com",
        "tsars5.com",
        "cosmicslot.com",
        "apuestamos.com",
        "playfortuna.com",
        "pokernox.com",
        "queenplay.com",
        "17slottica.com",
        "18slottica.com",
        "20slottica.com",
        "savaronacasino.com",
        "vulkanvegas1.com",
        "vulkanvegas3.com",
        "vulkanvegas5.com",
        "vulkanvegas6.com",
        "vulkanvegas7.com",
        "vulkanvegas8.com",
        "vulkanvegas9.com",
        "betfashiontv.com",
        "777slotsbay.com",
        "slottyway.com",
        "slottyway1.com",
        "slottyway2.com",
        "slottyway4.com",
        "slottyway5.com",
        "slottyway6.com",
        "slottyway7.com",
        "slottyway8.com",
        "slottyway9.com",
        "slottyway10.com",
        "slottyway11.com",
        "slottyway12.com",
        "vulkanvegas18.com",
        "vulkanvegas23.com",
        "vulkanvegas25.com",
        "vulkanvegas26.com",
        "vulkanvegas27.com",
        "vulkanvegas28.com",
        "vulkanvegas29.com",
        "vulkanvegas30.com",
        "vulkanvegas31.com",
        "vulkanvegas32.com",
        "vulkanvegas33.com",
        "vulkanvegas34.com",
        "vulkanvegas35.com",
        "vulkanvegas36.com",
        "vulkanvegas37.com",
        "vulkanvegas39.com",
        "vulkanvegas40.com",
        "vulkanvegas41.com",
        "vulkanvegas42.com",
        "vulkanvegas43.com",
        "vulkanvegas44.com",
        "vulkanvegas45.com",
        "vulkanvegas46.com",
        "vulkanvegas47.com",
        "vulkanvegas48.com",
        "vulkanvegas49.com",
        "vulkanvegas50.com",
        "vulkanvegas51.com",
        "vulkanvegas52.com",
        "vulkanvegas53.com",
        "vulkanvegas54.com",
        "vulkanvegas55.com",
        "admiralxxx.best",
        "vip.admiralxxx.net",
        "admiralxxx.club",
        "luckybirdcasino12.com",
        "booi.com",
        "ovitoonscasino.com",
        "betwin-773595.top",
        "winnings.com",
        "paripesa.com",
        "1-admiralxxx.site",
        "m.admiralxxx.casino",
        "admiralxxx.casino",
        "451vjadmiral-x.icu",
        "m.admiral-x.com",
        "admiral-x.com",
        "m.admiral-x3.com",
        "admiral-x3.com",
        "m.admiralx7.com",
        "win.admiral-x7.com",
        "m.admiral-x8.com",
        "win.admiral-x8.com",
        "m.admiral-x9.com",
        "admiralx9.com",
        "admiral-x10.com",
        "win.admiral-x14.com",
        "vip1.admiral-x17.com",
        "vip1.admiral-x18.com",
        "win.3.51argocasino.com",
        "betvoyager.com",
        "ggbet.com",
        "betzest.com",
        "arenabet.com",
        "iggbet.com",
        "slottica31.com",
        "slottica32.com",
        "slottica33.com",
        "slottica34.com",
        "slottica36.com",
        "slottica37.com",
        "slottica38.com",
        "slottica40.com",
        "21slottica.com",
        "22slottica.com",
        "25slottica.com",
        "26slottica.com",
        "casinolafiesta.com",
        "cosmicslot123.com",
        "wisho.com",
        "luckybirdcasino6.com",
        "luckybirdcasino7.com",
        "luckybirdcasino8.com",
        "luckybirdcasino9.com",
        "luckybirdcasino10.com",
        "luckybirdcasino11.com",
        "luckybirdcasino13.com",
        "luckybirdcasino14.com",
        "luckybirdcasino15.com",
        "argocasino.com",
        "kajot-casino.com",
        "lsbet741.com",
        "lsbet742.com",
        "lsbet746.com",
        "lsbet747.com",
        "reelemperor.com",
        "1vulkanvegas.com",
        "3vulkanvegas.com",
        "4vulkanvegas.com",
        "5vulkanvegas.com",
        "7vulkanvegas.com",
        "8vulkanvegas.com",
      ],
    ),
    const Institution(
      name: "RTK",
      ips: ["88.119.87.40", "92.61.36.174"],
      domains: [
        "themusiclt.com",
        "tophitai.com",
        "pdfknygos.net",
        "filmix.co",
        "yts.lt",
        "new-rus.tv",
        "newru.tv",
        "tebox.eu",
        "filmai.in",
        "torrent.ai",
        "hdxa.me",
        "bobfilm.xyz",
        "filmix.guru",
        "filmix.org.ua",
        "themusiclt.net",
        "knygos.in",
        "torrent.lt",
        "mp3.themusic.lt",
        "filmux.org",
        "knygos.net",
        "kinocoin.co",
        "filmux.net",
        "filmai.tv",
        "tartugi.com",
        "rezka.ag",
        "filmix.zone",
        "filmix.monster",
        "filmai.co",
        "gerifilmai.net",
        "changebook.net",
        "epubknygos.com",
        "knygos24.com",
        "el-knygos.eu",
        "pdfknygos.org",
        "skaitiniai.org",
        "filmux.online",
        "filmai.live",
        "filmai.se",
        "filmai.biz",
        "ziurek.org",
        "filmai.gokas.lt",
        "yts.mx",
        "knygos.site",
        "e-knygos.eu",
        "filmas.live",
        "serialai.online",
        "pdfknygos.club",
        "filmai.best",
        "filmai.to",
        "serialas.us.lt",
        "filmas.club",
        "serialai.in",
        "ltfilmai.online",
        "filmai.uk",
        "onlinefilmai.net",
        "filmix.cc",
        "ziuri.org",
        "ziuri.net",
        "tophitai.us",
        "filmas24.live",
        "filmai.eu",
        "filmai.pro",
        "filmaionline.net",
        "knygos.org",
        "aknygos.club",
        "yts.am",
        "yts.unblocked",
        "yts.ws",
        "yts.io",
        "yts.pm",
        "yts.unblocked.llc",
        "ytss.unblocked.is",
        "yts.unblocked.tw",
        "ytss.unblocked.to",
        "yts.unblocked.nz",
        "yts.unblocked.pw",
        "filmux.tv",
        "ziurim.gokas.lt",
        "tartugi.net",
        "hdrezka.ag",
        "tophitai.lt",
        "yst.lt",
        "filmai.org",
        "kinas.org",
        "filmai24.org",
        "ziuri.online",
        "ziurim.in",
        "ziurim.net",
        "serialas.online",
        "superfilmai.net",
        "filmai.us",
        "filmai.ucoz.org",
        "filmas.to",
        "kinas24.live",
        "filmux.live",
        "ziureti.online",
        "ziuri.me",
        "onlinefilmas.eu",
        "filmason.lt",
        "filmaionline.org",
        "filmas.tv",
        "filmaioso.lt",
        "siaubofilmai.online",
        "filmas.in",
        "filmainemokamai.ql.lt",
        "gerifilmai.org",
        "hdrezka.co",
        "efilmai.net",
        "films24.net",
        "balticword.eu",
        "visifilmai.net",
        "8filmai.org",
        "hdrezka.club",
        "filmux.cc",
        "filmai.ws",
        "hdrezka.me",
        "filmai.plus",
        "hdrezka.name",
        "filmas.co",
        "onlinefilmai.org",
        "hdrezka.tv",
        "elektronines.com",
        "pdfknygos.com",
        "hdrezka-ag.com",
        "bknygos.club",
        "mrhdrezka.com",
        "filmai.site",
        "filmas.site",
        "pdfknygos.biz",
        "8filmai.online",
        "filmai.link",
        "filmux.to",
        "filmix.ac",
        "betahdrezka.com",
        "efilmai.live",
        "filmix.cloud",
        "myhdrezka.com",
        "filmas.pro",
        "ziurim.org",
        "putlockerc.to",
        "bmovies.co",
        "kostanayturist.com",
        "torrent9.one",
        "cpasbien.sh",
        "yggtorrent.li",
        "oxtorrent.tv",
        "torrent9-super.com",
        "torrent9biz.fr",
        "torrent9.unblockninja.com",
        "torrent9.to",
        "pokeroynaonline.com",
        "oxtorrent.proxybit.work",
        "molkking.fr",
        "madame-coccinelle.fr",
        "legalwiki.in",
        "gktorrent.unbl0ck.xyz",
        "torrent9vf.fr",
        "torrent9-frech.fr",
        "t9-cpas.fr",
        "t9-club.com",
        "libertyvf-land-fr.fr",
        "oxtorrent.co",
        "cortesia.fr",
        "weareweart.fr",
        "cpasbienx.fr",
        "3cb.fr",
        "pdfknygynas.weebly.com",
        "scripsit.fr",
        "t9usenet.com",
        "torrent9.gg",
        "christelledubos.fr",
        "cpasbien2019.fr",
        "gktorrent.fr",
        "torrent9s.fr",
        "lyberty-landx.fr",
        "gktorrent.unblocknow.space",
        "torent9.cz",
        "torrent9-film.fr",
        "gktorrent-fr.fr",
        "quivoila-lefilm.fr",
        "cpasbien-tf.fr",
        "cpasbien.to",
        "cestpasbien-fr.fr",
        "cpasbiens-fr.fr",
        "fakenews.fyi",
        "wawacity.tv",
        "wiflix.eu",
        "torrent9-zone.fr",
        "socialistesmetropolitains.fr",
        "zone-telechargement.cloud",
        "cpddd.fr",
        "extreme-down.live",
        "speeddownfrance.fr",
        "cpasbien-site.fr",
        "sarp-decouverte-nature.fr",
        "torrent9t.fr",
        "yggtorrent.co",
        "filmux.life",
        "filmux.top",
        "karantinas.online",
        "thq.lt",
        "filmux.link",
        "filmaionline.com",
        "filmaivip.com",
        "ziureti.us.lt",
        "filmux.xyz",
        "8filmai.xyz",
        "filmux.us",
        "ziuret.online",
        "instahdrezka.com",
        "aghdrezka.com",
        "filmai.in.net",
        "filmaiin.club",
        "filmai.dev",
        "ziurim.club",
        "fonogramos-naujos.com",
        "ziuretionline.ql.lt",
        "8filmai.fun",
        "muzikoss.ucoz.com",
        "rezka.pw",
        "filmai.life",
        "topfilmai.online",
        "walden.lt",
        "filmaionline.ucoz.net",
        "serialurojus.com",
        "m-squarehotel.com",
        "8filmai.info",
        "filmai.io",
        "filmas.top",
        "serialai.live",
        "bknyga.club",
        "filmas.vip",
        "serialai.club",
        "filmux.club",
        "filmai.cc",
        "kinas.tv",
        "filmaiin.idmcrack.us",
        "rezka.io",
        "tgfm.in",
        "tgfm.to",
        "filmix.beer",
        "hdrezka.today",
        "kinastau.do.am",
        "nemokamatv.lt",
      ],
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Blokuoti domenai',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: DefaultTabController(
        length: data.length,
        child: Scaffold(
          appBar: AppBar(
            title: const Text('Blokuoti domenai'),
            bottom: TabBar(
              isScrollable: true,
              tabs: [
                for (final institution in data)
                  Tab(
                    text: institution.name,
                  ),
              ],
            ),
          ),
          body: TabBarView(
            children: [
              for (var i = 0; i < data.length; i++)
                InstitutionTab(institution: data[i]),
            ],
          ),
        ),
      ),
    );
  }
}

class InstitutionTab extends StatelessWidget {
  final Institution institution;

  const InstitutionTab({
    Key? key,
    required this.institution,
  }) : super(key: key);

  Future<bool> isDomainRegistered(String domain) async {
    // https://dns.google/resolve?name=visiaksasdasdasdas.lt&type=A&cd=true
    final response = await http.get(Uri.https(
      'dns.google',
      '/resolve',
      {
        'name': domain,
        'type': 'A',
        'cd': 'true',
      },
    ));

    if (response.statusCode == 200) {
      var jsonResponse =
          convert.jsonDecode(response.body) as Map<String, dynamic>;
      return jsonResponse['Status'] != 3;
    } else {
      print(
          'Google DNS request failed with status: ${response.statusCode} and $domain.');

      return false;
    }
  }

  Future<ResolvedDomain> resolveDomain(String domain) async {
    if (!await isDomainRegistered(domain)
        .onError((error, stackTrace) => true)) {
      return ResolvedDomain(
        domain: domain,
        resolvedIps: [],
        status: DomainStatus.nx,
      );
    }

    await Future.delayed(Duration(milliseconds: Random().nextInt(30)));

    try {
      final resolvedLookup = await InternetAddress.lookup(
        domain,
        type: InternetAddressType.IPv4,
      );

      final resolvedIps = resolvedLookup.map((e) => e.address).toList();

      if (resolvedIps.any((r) => institution.ips.contains(r))) {
        return ResolvedDomain(
          domain: domain,
          resolvedIps: resolvedIps,
          status: DomainStatus.blocked,
        );
      } else {
        return ResolvedDomain(
          domain: domain,
          resolvedIps: resolvedIps,
          status: DomainStatus.available,
        );
      }
    } on SocketException catch (ex) {
      print(ex.message);

      return ResolvedDomain(
        domain: domain,
        resolvedIps: [],
        status: DomainStatus.error,
      );
    }
  }

  Future<List<ResolvedDomain>> resolveDomains() {
    return Future.wait(
        institution.domains.map((d) => resolveDomain(d)).toList());
  }

  Widget _getLeadingForResolvedDomain(ResolvedDomain resolvedDomain) {
    switch (resolvedDomain.status) {
      case DomainStatus.available:
        return const CircleAvatar(
          backgroundColor: Colors.red,
          child: Icon(Icons.error_outline),
        );
      case DomainStatus.blocked:
        return const CircleAvatar(
          backgroundColor: Colors.green,
          child: Icon(Icons.check),
        );
      case DomainStatus.nx:
        return const CircleAvatar(
          backgroundColor: Colors.blue,
          child: Icon(Icons.lightbulb),
        );
      case DomainStatus.error:
        return const CircleAvatar(
          backgroundColor: Colors.orange,
          child: Icon(Icons.warning_amber),
        );
    }
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<List<ResolvedDomain>>(
      builder: (context, snapshot) {
        if (snapshot.hasData) {
          final items = snapshot.requireData
            ..sort((a, b) => a.status.index.compareTo(b.status.index));

          return Scaffold(
            floatingActionButton: FloatingActionButton(
              onPressed: () async {
                final availableDoamins = items
                    .where((e) => e.status == DomainStatus.available)
                    .toList();

                final domains =
                    availableDoamins.map((e) => e.domain).join("\n");

                final ips = availableDoamins
                    .map((e) => e.resolvedIps.join(", "))
                    .join("\n");

                await Clipboard.setData(
                    ClipboardData(text: "$domains\n\n$ips"));
              },
              child: const Icon(Icons.save),
            ),
            body: ListView.separated(
              itemCount: items.length + 1,
              separatorBuilder: (context, index) => const Divider(height: 1),
              itemBuilder: (context, index) {
                if (index == 0) {
                  return DataTable(headingRowHeight: 0, columns: <DataColumn>[
                    DataColumn(label: Container()),
                    DataColumn(label: Container()),
                  ], rows: [
                    for (final status in DomainStatus.values)
                      DataRow(
                        cells: [
                          DataCell(Text(status.pluralName)),
                          DataCell(
                            Text(
                              items
                                  .where((r) => r.status == status)
                                  .length
                                  .toString(),
                            ),
                          ),
                        ],
                      ),
                  ]);
                }

                final resolvedDomain = items[index - 1];

                return ListTile(
                  leading: _getLeadingForResolvedDomain(resolvedDomain),
                  title: Text(resolvedDomain.domain),
                  subtitle: Text(
                    "${resolvedDomain.status.name}\n"
                    "${resolvedDomain.resolvedIps.join(" ")}",
                  ),
                  trailing: const Icon(Icons.chevron_right),
                  onTap: () => launch("http://${resolvedDomain.domain}"),
                );
              },
            ),
          );
        }

        if (snapshot.hasError) {
          return Text(snapshot.error?.toString() ?? "Unknown error");
        }

        return const Center(child: CircularProgressIndicator());
      },
      future: resolveDomains(),
    );
  }
}
